### ISSUE TITLE
w3lib 1.14 breaks scrapy 0.24.6 usage of urlparse.urldefrag

### ISSUE THREAD

**Issue by avish** [scrapy/w3lib#54]
```shell
$ pip install scrapy==0.24.6
```
This currently pulls in w3lib 1.14.0 or 1.14.1.

```shell
$ python -c "from scrapy import Request; req = Request(url='http://www.example.com')"
```

Gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avish/.virtualenvs/w3lib-bug/local/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 26, in __init__
    self._set_url(url)
  File "/home/avish/.virtualenvs/w3lib-bug/local/lib/python2.7/site-packages/scrapy/http/request/__init__.py", line 52, in _set_url
    self._url = escape_ajax(safe_url_string(url))
  File "/home/avish/.virtualenvs/w3lib-bug/local/lib/python2.7/site-packages/scrapy/utils/url.py", line 102, in escape_ajax
    defrag, frag = urlparse.urldefrag(url)
AttributeError: 'function' object has no attribute 'urldefrag'
```

Downgrading to `w3lib==1.13.0` fixes this issue.

The problem doesn't happen with `scrapy>=1.0` (but 1.0 introduced breaking changes so some projects still use 0.24)

**Comment by kmike** [comment]
I think we should add `__all__` to w3lib.utils.url to prevent such issues (https://github.com/scrapy/w3lib/pull/45#discussion_r57146718).

**Comment by redapple** [comment]
@avish , [w3lib v1.14.2 is now on PyPI](https://pypi.python.org/pypi/w3lib/1.14.2).
Can I ask you to confirm if it fixes the issue for you?

**Comment by avish** [comment]
Sorry for the late reply, @redapple. Yes, `w3lib==1.14.2` is now pulled by default with scrapy 0.24 and fixes the issue.
